### ISSUE TITLE
Update to 3.7.0

### ISSUE THREAD

**Issue by aadcg** [KikyTokamuro/nyxt-fedora#1]
Hi @KikyTokamuro. To bump to the latest version, please add files `/app/share/metainfo/nyxt.metainfo.xml` and `/app/share/icons/hicolor/scalable/apps/nyxt.svg` to the package definition. The build should be successful with those changes. 

Thanks!

**Comment by KikyTokamuro** [comment]
Hello @aadcg. I updated the version, but the new package is not yet built due to systematic failures in Fedora Copr (https://github.com/fedora-copr/copr/issues/2906), as soon as the problem is solved I will rebuild the package.

**Comment by KikyTokamuro** [comment]
I built it taking into account their workaround.
Version 3.7.0 is now available.

Thank you!
